kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: apidevs
  namespace: openhackapi
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: apidev-access
  namespace: openhackapi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apidevs
subjects:
- kind: Group
  namespace: openhackapi
  name: 1124749c-faf0-4afb-8e4b-4050dd1476e8