apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openhack-ingressweb
  namespace: openhackweb
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tripviewer
          servicePort: 80
        path: /(.*)
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openhack-ingressweb-images
  namespace: openhackweb
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /images/$2
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tripviewer
          servicePort: 80
        path: /images(/|$)(.*)