apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: trips
  name: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      run: trips
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: trips
    spec:
      containers:
      - image: registryfiw7378.azurecr.io/trips:0.9
        name: trips
        resources: {}
status: {}
