apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: tripviewer
  name: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tripviewer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: tripviewer
    spec:
      containers:
      - image: registryfiw7378.azurecr.io/tripviewer:0.9
        name: tripviewer
        imagePullPolicy: Always
        resources: {}
status: {}
