apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: user-java
  name: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      run: user-java
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: user-java
    spec:
      containers:
      - image: registryfiw7378.azurecr.io/user-java:0.9
        name: user-java
        resources: {}
status: {}
