apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: userprofile
  name: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      run: userprofile
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: userprofile
    spec:
      containers:
      - image: registryfiw7378.azurecr.io/userprofile:0.9
        name: userprofile
        resources: {}
status: {}
